spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/fishing-ecsite
    username: postgres
    password: postgres
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: jyo00syuukau99@gmail.com
#    password: fttoxmfkzwdpvexl
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls.enable: true    
